### ISSUE TITLE
Build fails with GCC-6.1

### ISSUE THREAD

**Issue by ajaypanyala** [pulsar-chem/Pulsar-Core#41]
The build fails when using GCC-6.1 with the following error

```
Building CXX object CMakeFiles/pulsar_core.dir/system/CrystalFunctions.cpp.o
/opt/compilers/gcc6/include/c++/6.1.0/bits/stl_algo.h:4210:5: note:   template argument deduction/substitution failed:
/home/panyala/git/Pulsar/Pulsar-Core/pulsar/system/CrystalFunctions.cpp:29:64: note:   candidate expects 5 arguments, 4 provided
     std::transform(Angles.begin(),Angles.end(),CosA.begin(),cos);
```

Commenting the above line as a workaround for now since it's not used by the integrals code.

**Comment by bennybp** [comment]
Lookes to be due to some craziness with the overloaded math functions, which doesn't play well with std::transform.

Should be fixed with commit 3fef53b413116bf890efcf5db58467fe9172de7b . Give it a try

**Comment by ajaypanyala** [comment]
@bennybp  It works now. I am using HFGo branch. Could you please rebase HFGo with this change. Thanks!

**Comment by ryanmrichard** [comment]
@ajaypanyala HFGo is merged with the trunk now so you should be able to just us master from now on.  Also, as a heads up, @bennybp and I agreed that we should switch the integrals API a bit so that it matches most existing libraries (instead of getting a double* back, you'll give it a double*).  When that change goes live I'll update Pulsar-LibInt, and Pulsar-SCF with it too.
